import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Card, Button, Field, Muted, Pill, Title } from '../components/UI';
import { COLORS } from '../theme';
import { sharedGet, sharedSet } from '../storage';

export default function ChatTab({profile}){
  const [rooms,setRooms]=useState(['Crew']);const [room,setRoom]=useState('Crew');const [messages,setMessages]=useState([]);const [text,setText]=useState('');const [newRoom,setNewRoom]=useState('');const [streak,setStreak]=useState(0);
  const load=async()=>{setRooms(await sharedGet('chat:rooms',['Crew']));setMessages(await sharedGet(`chat:${room}`,[]));const st=await sharedGet('chat:streaks',{});setStreak(st[profile.nickname]?.count||0)};
  useEffect(()=>{load();const id=setInterval(load,3500);return()=>clearInterval(id)},[room]);
  const send=async()=>{if(!text.trim())return;const next=[...messages,{id:Date.now(),by:profile.nickname,text:text.trim(),at:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}].slice(-100);setMessages(next);setText('');await sharedSet(`chat:${room}`,next);const all=await sharedGet('chat:streaks',{});const today=new Date().toISOString().slice(0,10);const y=new Date();y.setDate(y.getDate()-1);const yesterday=y.toISOString().slice(0,10);const old=all[profile.nickname]||{};const count=old.last===today?(old.count||1):old.last===yesterday?(old.count||0)+1:1;const updated={...all,[profile.nickname]:{last:today,count}};await sharedSet('chat:streaks',updated);setStreak(count)};
  const addRoom=async()=>{const n=newRoom.trim();if(!n||rooms.includes(n))return;const next=[...rooms,n].slice(0,12);setRooms(next);setNewRoom('');setRoom(n);await sharedSet('chat:rooms',next)};
  return <View style={styles.stack}><Card><Title>Chat</Title><Text style={styles.streak}>Chat-Streak: {streak} Tag{streak===1?'':'e'}</Text><Muted>Im Emulator läuft der „shared“-Speicher zunächst lokal. Für echte Chats zwischen mehreren Handys wird später ein Online-Backend angeschlossen.</Muted><View style={styles.wrap}>{rooms.map(r=><Pill key={r} label={r} active={room===r} onPress={()=>setRoom(r)}/>)}</View><View style={styles.row}><View style={{flex:1}}><Field value={newRoom} onChangeText={setNewRoom} placeholder="Neuer Raum oder DM:Name"/></View><Button title="+" onPress={addRoom}/></View></Card><Card><Title small>{room}</Title>{messages.length?messages.map(m=><View key={m.id} style={[styles.msg,m.by===profile.nickname&&styles.mine]}><Text style={styles.meta}>{m.by} · {m.at}</Text><Text style={styles.body}>{m.text}</Text></View>):<Muted>Noch keine Nachrichten.</Muted>}<Field value={text} onChangeText={setText} placeholder="Nachricht…" multiline/><Button title="Senden" onPress={send}/></Card></View>
}
const styles=StyleSheet.create({stack:{gap:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},row:{flexDirection:'row',gap:8,alignItems:'center'},msg:{backgroundColor:COLORS.panel2,padding:10,borderRadius:12,alignSelf:'stretch'},mine:{borderLeftWidth:3,borderLeftColor:COLORS.volt},meta:{color:COLORS.muted,fontSize:11,fontWeight:'800'},streak:{color:COLORS.volt,fontWeight:'900'},body:{color:COLORS.text,fontSize:15,marginTop:3,lineHeight:20}});
