import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps';
import { Card, Button, Field, Muted, Notice, Pill, Title } from '../components/UI';
import { COLORS } from '../theme';
import { localGet, localSet } from '../storage';
import { aiConfigured, searchParksAI, transitAI, weatherAI } from '../services/ai';
import { openGoogleImages, openGoogleMapsSearch, openTransitRoute } from '../services/maps';

const DEFAULT_REGION={latitude:51.1657,longitude:10.4515,latitudeDelta:8,longitudeDelta:8};

export default function ParksTab({sport,profile}){
  const [parks,setParks]=useState([]);const [saved,setSaved]=useState({});const [covered,setCovered]=useState(false);const [floodlight,setFloodlight]=useState(false);const [view,setView]=useState('map');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [region,setRegion]=useState(DEFAULT_REGION);const [travelOpen,setTravelOpen]=useState(null);const [travelText,setTravelText]=useState('');const [weather,setWeather]=useState(null);
  useEffect(()=>{(async()=>{const p=await localGet(`parks:${sport.id}`,[]);setParks(p);setSaved(await localGet(`parks:saved:${sport.id}`,{}));if(p[0]?.latitude&&p[0]?.longitude)setRegion({latitude:+p[0].latitude,longitude:+p[0].longitude,latitudeDelta:.5,longitudeDelta:.5})})()},[sport.id]);
  const filtered=useMemo(()=>parks.filter(p=>(!covered||p.indoor===true)&&(!floodlight||p.flutlicht===true)),[parks,covered,floodlight]);
  const search=async()=>{setBusy(true);setNotice('');try{if(!aiConfigured())throw new Error('Für die echte KI-Websuche zuerst den KI-Proxy starten. Du kannst Google Maps trotzdem direkt öffnen.');const p=await searchParksAI(sport,profile.home,{covered,floodlight});const valid=(Array.isArray(p)?p:[]).filter(x=>Number.isFinite(+x.latitude)&&Number.isFinite(+x.longitude));setParks(valid);await localSet(`parks:${sport.id}`,valid);if(valid[0])setRegion({latitude:+valid[0].latitude,longitude:+valid[0].longitude,latitudeDelta:.5,longitudeDelta:.5});if(!valid.length)setNotice('Die Suche hat keine verwertbaren Anlagen mit Koordinaten geliefert.')}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const googleSearch=()=>openGoogleMapsSearch(`${sport.parkTypes.join(' oder ')} ${sport.name} ${profile.home}`);
  const toggleSave=async(p)=>{const id=p.name+'|'+p.ort;const next={...saved};if(next[id])delete next[id];else next[id]={rating:0,note:''};setSaved(next);await localSet(`parks:saved:${sport.id}`,next)};
  const updateSaved=async(p,patch)=>{const id=p.name+'|'+p.ort;const next={...saved,[id]:{...(saved[id]||{}),...patch}};setSaved(next);await localSet(`parks:saved:${sport.id}`,next)};
  const runWeather=async()=>{setBusy(true);setNotice('');try{const w=await weatherAI(profile.home,sport);setWeather(w);if(w?.nass===true)setCovered(true)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const runTransit=async(p,id)=>{setTravelOpen(id);setTravelText('Suche Verbindung…');try{setTravelText(await transitAI(sport,profile.home,p))}catch(e){setTravelText(e.message)}};
  return <View style={styles.stack}>{notice?<Notice>{notice}</Notice>:null}<Card><Title color={sport.color}>Parks · Google Maps</Title><Muted>Gesucht wird passend zu {sport.name}: {sport.parkTypes.join(', ')}.</Muted><View style={styles.wrap}><Pill label="🗺️ Karte" active={view==='map'} onPress={()=>setView('map')}/><Pill label="☷ Liste" active={view==='list'} onPress={()=>setView('list')}/></View><View style={styles.filter}><Text style={styles.filterText}>🏠 nur überdacht</Text><Switch value={covered} onValueChange={setCovered} trackColor={{true:COLORS.volt}}/></View><View style={styles.filter}><Text style={styles.filterText}>🌙 nur mit Flutlicht</Text><Switch value={floodlight} onValueChange={setFloodlight} trackColor={{true:COLORS.volt}}/></View><Button title={busy?'Suche läuft…':'🔎 Echte Anlagen per KI-Websuche'} disabled={busy} onPress={search}/><Button title="In Google Maps suchen" tone="ice" onPress={googleSearch}/></Card>
  <Card><Title small>🌦️ Wetter am Wohnort</Title><Button title="Wetter aktuell prüfen" tone="dark" disabled={busy} onPress={runWeather}/>{weather?<View style={styles.weather}><Text style={styles.body}>Jetzt: {String(weather.jetzt||'–')}</Text><Text style={styles.body}>Später: {String(weather.spaeter||'–')}</Text><Text style={styles.body}>Morgen: {String(weather.morgen||'–')}</Text><Text style={styles.body}>Empfehlung: {String(weather.empfehlung||'–')}</Text>{weather.schneehoehe?<Text style={styles.body}>Schneehöhe: {String(weather.schneehoehe)}</Text>:null}{weather.pistenzustand?<Text style={styles.body}>Piste: {String(weather.pistenzustand)}</Text>:null}{weather.nass===true?<Muted>Es ist nass: „nur überdacht“ wurde automatisch aktiviert.</Muted>:null}</View>:<Muted>Datum und aktuelle Uhrzeit werden bei der Wetterabfrage mitgeschickt.</Muted>}</Card>
  {view==='map'?<Card style={{padding:0,overflow:'hidden'}}><MapView provider={PROVIDER_GOOGLE} style={styles.map} region={region} onRegionChangeComplete={setRegion}>{filtered.map((p,i)=><Marker key={`${p.name}-${i}`} coordinate={{latitude:+p.latitude,longitude:+p.longitude}} title={p.name} description={`${p.typ||''} · ${p.erlaubnis||''}`} pinColor={sport.color}/>)}</MapView></Card>:null}
  {filtered.length===0?<Card><Muted>Noch keine Park-Liste. Starte die KI-Websuche oder öffne die passende Suche direkt in Google Maps.</Muted></Card>:filtered.map((p,i)=>{const id=p.name+'|'+p.ort;const fav=saved[id];return <Card key={id+i}><Pressable onPress={()=>openGoogleImages(`${p.name} ${p.ort} ${sport.name}`)}><Title small color={sport.color}>{p.name}</Title><Muted>{p.ort} · {p.typ} · {p.entfernungKm??'?'} km {p.himmelsrichtung?`· ${p.himmelsrichtung}`:''}</Muted></Pressable><Text style={styles.body}>{p.ausstattung}</Text><Text style={styles.body}>{p.begruendung}</Text><Notice tone={String(p.erlaubnis||'').includes('unklar')?'pink':'volt'}>{p.erlaubnis||'Erlaubnis unklar – vorher anrufen'}</Notice><View style={styles.wrap}><Pill label={p.indoor?'🏠 Indoor':'🌤️ Outdoor'} active={false}/><Pill label={p.flutlicht===true?'🌙 Flutlicht':p.flutlicht===false?'Ohne Flutlicht':'Flutlicht ?'} active={false}/></View><Button title={fav?'★ Gemerkt':'☆ Merken'} tone="dark" onPress={()=>toggleSave(p)}/>{fav?<><Text style={styles.label}>Bewertung</Text><View style={styles.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>updateSaved(p,{rating:n})}><Text style={[styles.star,n<=fav.rating&&{color:COLORS.volt}]}>★</Text></Pressable>)}</View><Field value={fav.note||''} onChangeText={note=>updateSaved(p,{note})} placeholder="Notiz zum Spot" multiline/></>:null}<View style={styles.wrap}><Button title="🖼️ Bilder" compact tone="ice" onPress={()=>openGoogleImages(`${p.name} ${p.ort} ${sport.name}`)}/><Button title="🚆 Anreise" compact tone="dark" onPress={()=>setTravelOpen(travelOpen===id?null:id)}/></View>{travelOpen===id?<View style={styles.travel}><Button title="Google Maps · Öffis" onPress={()=>openTransitRoute(profile.home,`${p.name}, ${p.ort}`)}/><Button title="Zug/Bus per KI prüfen" tone="dark" onPress={()=>runTransit(p,id)}/>{travelText?<Text style={styles.body}>{travelText}</Text>:null}</View>:null}</Card>})}</View>
}
const styles=StyleSheet.create({stack:{gap:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},filter:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',minHeight:48,borderTopWidth:1,borderTopColor:COLORS.line},filterText:{color:COLORS.text,fontSize:15,fontWeight:'700'},map:{height:360,width:'100%'},body:{color:COLORS.text,lineHeight:21},weather:{gap:5,backgroundColor:COLORS.panel2,padding:12,borderRadius:12},stars:{flexDirection:'row',gap:7},star:{fontSize:28,color:COLORS.line},label:{color:COLORS.muted,fontWeight:'800'},travel:{gap:8,backgroundColor:COLORS.panel2,padding:12,borderRadius:12}});
